### ISSUE TITLE
pinv2 deprecated

### ISSUE THREAD

**Issue by dannyrichy** [theochem/procrustes#197]
Hello, 
Since scipy 1.9.0 , the function pinv2 has been subsumed in pinv, is it possible to remove it's use in generic.py 

P.S
Attaching link to the release notes [https://docs.scipy.org/doc/scipy/release.1.9.0.html?highlight=pinv2](https://docs.scipy.org/doc/scipy/release.1.9.0.html?highlight=pinv2)

**Comment by FanwangM** [comment]
Hi! Thank you for your interest in our package. @the-nihilist-ninja 
If you install the latest version of our package from the source, `pinv2` has been replaced by `pinv`. 

I am going to close this issue for now. But please feel free to reopen this issue or create a new one if needed.

**Comment by lgrcia** [comment]
Thanks for the tips. Would that be possible to update it on pypi?

**Comment by PaulWAyers** [comment]
Updating on pypi should be possible with cardboardlint.

**Comment by PaulWAyers** [comment]
Yep, we can resolve this by requiring old versions of scipy, which is fine. But probably better to evolve to the newest versions of scipy anyway.

**Comment by FanwangM** [comment]
Can you (or who encountered the problem) provide an example showing the problem of using `pinv` function? I will add this as a test in the fix. Thanks.

@PaulWAyers

**Comment by PaulWAyers** [comment]
The issue showed up in `gopt`, but I remembered that the same issue appears here. @Moham21 should have an example of a matrix that's problematic.

**Comment by PaulWAyers** [comment]
@moham21 can you give an example of a matrix whre `scipy.pinv` doesn't work but `scipy.pinv2` does work?

**Comment by Moham21** [comment]
> @Moham21 can you give an example of a matrix whre `scipy.pinv` doesn't work but `scipy.pinv2` does work?

I checked the test errors that I had so far and I didn't come across an inverse problem, but rather an eigenvalue conversion. And we have decided to `try numpy` and `except scipy` and that helped for the most part.

**Comment by FanwangM** [comment]
Do you still have a matrix example to show how the `pinv2` failed? This would be useful for me to build a test. Thank you. @Moham21

**Comment by PaulWAyers** [comment]
I talked to @Moham21 and the examples she had were from the eigenvalue problem. She was constructing a generalized inverse, but doing it "by hand" using the eigenvalues. 

As I recall, the examples that failed where ones where the matrix had several rows and/or columns of zeros. I think a nilpotent matrix might be a good example, but I did not confirm this.

**Comment by peekxc** [comment]
Please update and remove the requirement `SciPy >= 1.5.0`; per this issue, this package is not compatible with later scipy versions, as `pinv2` will trigger an `ImportError`

**Comment by PaulWAyers** [comment]
@FanwangM can you fix this?

We may need to move to the type of workflow we use in `Gopt` (@Moham21 or @marco-2023 ) can explain it, as the `Scipy` and `Numpy` pseudoinverses sacrifice robustness on the alter of speed. However, our little try-except script where we add a tiny bit of noise when things fail tends to work no matter what, and is good enough for this application.

**Comment by PaulWAyers** [comment]
@FanwangM can you fix this?

We may need to move to the type of workflow we use in `Gopt` (@Moham21 or @marco-2023 ) can explain it, as the `Scipy` and `Numpy` pseudoinverses sacrifice robustness on the alter of speed. However, our little try-except script where we add a tiny bit of noise when things fail tends to work no matter what, and is good enough for this application.

**Comment by FanwangM** [comment]
The original problem with this issue was I was not able to release a new version of `qc-procrustes`.  I will try to figure out how to release a new version with the current GitHub Action workflow. Otherwise, I will build a new workflow for release it. The trick of adding noise to make the pesudoinverse work will also be added.

**Comment by PaulWAyers** [comment]
Ah, so it's a pip issue. If the current source code already has it fixed, then @peekxc can install from source and there will not be an issue.

**Comment by peekxc** [comment]
@PaulWAyers this does not resolve the issue; the issue is I want to contribute to a library that depends on this package.

Yes, I can install this qc-procrustes from source fine, but I cannot use it with other software, as it is tied to a now out of date scipy/numpy version range.

**Comment by FanwangM** [comment]
@peekxc I am somewhat confused by your comments. We can try to update the version constraint to be `SciPy > 1.9.0`. But I don't understand why `SciPy >= 1.5.0` leads to incompatibility issues of the later Scipy version because it only forces the virtual environment to use the newer versions of `SciPy`.  I created a new environment with Python 3.11 and installed the source codes of our package in the main branch leading to the installation of `SciPy` with version 1.14.1. The only case it does not work because of the version constraint of `SciPy` is the other package uses older `SciPy` versions. A minimal example to reproduce the errors or more explanations would be very helpful for me to understand the problem. Thanks again for helping us improve our package.

**Comment by peekxc** [comment]
> But I don't understand why SciPy >= 1.5.0 leads to incompatibility issues of the later Scipy version because it only forces the virtual environment to use the newer versions of SciPy. I created a new environment with Python 3.11 and installed the source codes of our package in the main branch leading to the installation of SciPy with version 1.14.1. The only case it does not work because of the version constraint of SciPy is the other package uses older SciPy versions.

Yes, there are two issues here:
- `qc-procrustes` is incompatible the newest numpy/scipy releases
- The readme docs are wrong (states SciPy >= 1.5, should be < 1.9.0)
  
The issue of whether the source distribution working is irrelevant for me (it is though :)); 

Packages and resolvers depend on *PyPI distributions* (or conda repos) 

> I created a new environment with Python 3.11 and installed the source codes of our package in the main branch leading to the installation of SciPy with version 1.14.1.

This only works for me for source installations installed separately. If you create *any* package and add: 
```toml
dependencies = [
  "numpy", 
  "scipy", 
  "qc-procrustes"
]
```
to the `pyproject.toml`, the package will by non-functional, because `pip install` will install from PyPI only. Indeed, just importing the package for me causes the error: 

```bash
Python 3.10.9 (main, Jan 11 2023, 09:18:20) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import procrustes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mpiekenbrock/opt/miniconda3/envs/ml/lib/python3.10/site-packages/procrustes/__init__.py", line 39, in <module>
    from procrustes.generic import *
  File "/Users/mpiekenbrock/opt/miniconda3/envs/ml/lib/python3.10/site-packages/procrustes/generic.py", line 29, in <module>
    from scipy.linalg import pinv, pinv2
ImportError: cannot import name 'pinv2' from 'scipy.linalg' (/Users/mpiekenbrock/opt/miniconda3/envs/ml/lib/python3.10/site-packages/scipy/linalg/__init__.py)
```

>  The only case it does not work because of the version constraint of SciPy is the other package uses older SciPy versions.

Per the above comment, because the PyPI version of `qc-procrustes` doesn't work with the newest versions of numpy/scipy, I *have* to target an earlier version: 

```toml
dependencies = [
  "numpy >= 1.18.5, < 2.0", 
  "scipy <= 1.9.0",
  "qc-procrustes"
]
```

This works in Python 3.9, but not in 11:

```bash
mamba create -n testenv python=3.11 "numpy >= 1.18.5, < 2.0" "scipy < 1.9.0"
```

Yields a slew of resolver conflicts: 
```
...
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ python 3.11**  is requested and can be installed;
    └─ scipy <1.9.0  is not installable because there are no viable options
       ├─ scipy [0.19.1|1.0.0|...|1.2.1] would require
       │  └─ python >=2.7,<2.8.0a0 , which conflicts with any installable versions previously reported;
       ├─ scipy [0.19.1|1.0.0|1.0.1|1.1.0] would require
       │  └─ python >=3.5,<3.6.0a0 , which conflicts with any installable versions previously reported;
       ├─ scipy [0.19.1|1.0.0|...|1.5.2] would require
       │  └─ python >=3.6,<3.7.0a0 , which conflicts with any installable versions previously reported;
       ├─ scipy [1.1.0|1.2.0|...|1.7.3] would require
       │  └─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
       ├─ scipy [1.3.1|1.4.1|...|1.7.3] would require
       │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
       ├─ scipy [1.5.2|1.6.0|...|1.7.3] would require
       │  └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
       ├─ scipy 1.7.3 would require
       │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
       └─ scipy [0.17.1|0.18.0|...|1.8.1] conflicts with any installable versions previously reported.
critical libmamba Could not solve for environment specs
```

**Comment by FanwangM** [comment]
Thanks a lot for sharing the detailed information. I will take a look very soon, but it may take some time as I don't have access to the PyPI release for now.

**Comment by PaulWAyers** [comment]
@peekxc I think you are having issues with your `pyproject.toml` file. You can install from source there via a command like
    `qc-procrustes = { git = "https://github.com/theochem/procrustes.git", branch = "master"}`
which also ensuers that you always get the latest version.

We will get it so that we can use the latest version of scipy; it is just a bit of work since, at least in some of the cases we tested, the SVD didn't all the time (which is why we were using an alternative algorithm in the first place).

**Comment by PaulWAyers** [comment]
@FanwangM will say more, but I think the new release should fix things. We have a workaround for the "SVD fails to converge" error but it seems that the issue will probably be revised in the next scipy release (as one could do SVD with a specified driver routine, though this may not filter down to the pinv yet).

https://github.com/scipy/scipy/pull/21247

**Comment by FanwangM** [comment]
The new release of version 1.1.0 addresses the issue of pinv2 by using the updated version of `SciPy`. Now people can install the new release with `pip`. We also added a try-except statement to deal with the not converged cases of computing the (Moore-Penrose) pseudo-inverse of a matrix. This should have solved the problem.  If not, please feel to reopen it. @peekxc
